zip:
	cd ..; rm LlamaXML.zip; /usr/bin/find LlamaXML -name '.svn' -prune -o -name 'LlamaXML_Data' -prune -o -name '*.d' -prune -o -name '*.o' -prune -o -name '*~' -prune -o -name '.DS_Store' -prune -o -name 'build' -prune -o -name 'LlamaXML Data' -prune -o -name 'Debug' -prune -o -name '*.lib' -prune -o -name '*.mcp' -prune -o -print | zip LlamaXML.zip -@
