SHELL=/bin/zsh

zip:
	rm -f LlamaXML.zip
	cd ..; zip -r LlamaXML/LlamaXML.zip LlamaXML/**/*.(h|cpp|txt|html|xml|pbxproj|sln|vcproj|mcp|png|gif|css) LlamaXML/Palm/PODS/.*project LlamaXML/Palm/PODS/makefile*

