zip:
	cd ..; rm LlamaXML.zip; /usr/bin/find LlamaXML -name '.svn' -prune -o -name 'LlamaXML_Data' -prune -o -name '*.d' -prune -o -name '*.o' -prune -o -name "*~" -prune -o -print | zip LlamaXML.zip -@
